### ISSUE TITLE
Code release ETA

### ISSUE THREAD

**Issue by Inferencer** [XChenZ/invertAvatar#1]
Do you have any plans to opensource this research? 

I don't know what they are putting in your coffee at Tsinghua University, whatever it is need some.

 "The primary aims when developing a digital head avatar are two-fold: high fidelity and efficiency" I couldn't agree more, I also haven't seen an inversion that's high fidelity so that's a new one for me, Incremental GAN Inversion is very clever.

**Comment by XChenZ** [comment]
Thanks for your attention! We plane to opensource the project upon the paper acceptance.
