### ISSUE TITLE
Attribute editing

### ISSUE THREAD

**Issue by Inferencer** [XChenZ/invertAvatar#2]
You ever thought about progressing with this inversion for attribute editing on monocular videos, such as gaze redirection, age, facial hair, makeup transfer & style transfer, facial expressions i.e fear, happy surprised etc 
This inversion will surely be adopted by those with the above task in mind I was just curious if that was something your team are also interested in?

**Comment by XChenZ** [comment]
This is an interesting task, and I believe our inversion framework has potential to be adapted for this task. Currently, we have not explored in this direction.
